version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - ./data:/app/data
    networks:
      - product-desc-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - product-desc-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - product-desc-network

volumes:
  ollama_data:

networks:
  product-desc-network:
    driver: bridge
